// Generated by Copilot
using System.Collections.Generic;

namespace DocIngest.Core;

/// <summary>
/// Represents a document consisting of a subfolder and its related files.
/// </summary>
public class Document
{
    /// <summary>
    /// Gets or sets the path of the subfolder representing this document.
    /// </summary>
    public string Path { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the name of the document (derived from the subfolder name).
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the list of files in this document.
    /// </summary>
    public List<FileInfo> Files { get; set; } = new();

    /// <summary>
    /// Gets or sets the extracted text content of the document.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the list of tags for categorization.
    /// </summary>
    public List<string> Tags { get; set; } = new();

    /// <summary>
    /// Gets or sets the list of insights extracted from the document.
    /// </summary>
    public List<string> Insights { get; set; } = new();

    /// <summary>
    /// Gets or sets the list of paths to processed document files.
    /// </summary>
    public List<string> ProcessedDocuments { get; set; } = new();
}

/// <summary>
/// Simple representation of a file's metadata.
/// </summary>
public class FileInfo
{
    /// <summary>
    /// Gets or sets the full path of the file.
    /// </summary>
    public string Path { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the name of the file.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the last modified date of the file.
    /// </summary>
    public DateTime LastModified { get; set; }

    /// <summary>
    /// Gets or sets the size of the file in bytes.
    /// </summary>
    public long Size { get; set; }
}