// Generated by Copilot
using Microsoft.Extensions.Logging;

namespace DocIngest.Core.Services;

/// <summary>
/// Implementation of IDeliveryService that delivers documents to organized local folders.
/// Folder structure is determined by the organizationPathFunc.
/// </summary>
public class FolderDeliveryService : IDeliveryService
{
    private readonly string _baseDeliveryPath;
    private readonly ILogger<FolderDeliveryService> _logger;

    public FolderDeliveryService(string baseDeliveryPath, ILogger<FolderDeliveryService> logger)
    {
        _baseDeliveryPath = baseDeliveryPath;
        _logger = logger;
    }

    public async Task DeliverAsync(Document document, Func<Document, string> organizationPathFunc)
    {
        var relativePath = organizationPathFunc(document);
        var targetDir = Path.Combine(_baseDeliveryPath, relativePath);
        Directory.CreateDirectory(targetDir);

        foreach (var processedFile in document.ProcessedFiles)
        {
            var filePath = processedFile.Path;
            var fileName = Path.GetFileName(filePath);
            var targetPath = Path.Combine(targetDir, fileName);
            File.Copy(filePath, targetPath, overwrite: true);
            _logger.LogInformation($"Delivered {fileName} to {targetPath}");
        }
    }
}