// Generated by Copilot
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace DocIngest.Core.Services;

/// <summary>
/// Implementation of IDeliveryService that delivers documents to organized local folders.
/// </summary>
public class FolderDeliveryService : IDeliveryService
{
    private readonly string _baseDeliveryPath;
    private readonly ILogger<FolderDeliveryService> _logger;

    public FolderDeliveryService(string baseDeliveryPath, ILogger<FolderDeliveryService> logger)
    {
        _baseDeliveryPath = baseDeliveryPath;
        _logger = logger;
    }

    public async Task DeliverAsync(Document document, string organizationCriteria)
    {
        var organizationKey = GetOrganizationKey(document, organizationCriteria);
        var targetDir = Path.Combine(_baseDeliveryPath, organizationKey);
        Directory.CreateDirectory(targetDir);

        foreach (var filePath in document.ProcessedDocuments)
        {
            var fileName = Path.GetFileName(filePath);
            var targetPath = Path.Combine(targetDir, fileName);
            File.Copy(filePath, targetPath, overwrite: true);
            _logger.LogInformation($"Delivered {fileName} to {targetPath}");
        }
    }

    private string GetOrganizationKey(Document document, string criteria)
    {
        // By default, organize by date created (full date of the document folder)
        var dirInfo = new DirectoryInfo(document.Path);
        return dirInfo.CreationTime.ToString("yyyy-MM-dd");
    }
}