// Generated by Copilot
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Text.RegularExpressions;

namespace DocIngest.Core.Services;

/// <summary>
/// Implementation of IDeliveryService that delivers documents to organized local folders.
/// Folder structure: organizationCriteria / [documentName] / files (documentName omitted when criteria is "name").
/// Supports organization by: type (first tag), date (yyyy-MM-dd), year (yyyy), month (yyyy-MM), name (document name).
/// Defaults to date-based organization.
/// </summary>
public class FolderDeliveryService : IDeliveryService
{
    private readonly string _baseDeliveryPath;
    private readonly ILogger<FolderDeliveryService> _logger;

    public FolderDeliveryService(string baseDeliveryPath, ILogger<FolderDeliveryService> logger)
    {
        _baseDeliveryPath = baseDeliveryPath;
        _logger = logger;
    }

    public async Task DeliverAsync(Document document, string organizationCriteria)
    {
        var organizationKey = GetOrganizationKey(document, organizationCriteria);
        var targetDir = organizationCriteria.ToLowerInvariant() == "name"
            ? Path.Combine(_baseDeliveryPath, organizationKey)
            : organizationCriteria.ToLowerInvariant() == "month"
            ? Path.Combine(_baseDeliveryPath, organizationKey)
            : Path.Combine(_baseDeliveryPath, organizationKey, document.Name);
        Directory.CreateDirectory(targetDir);

        foreach (var processedFile in document.ProcessedFiles)
        {
            var filePath = processedFile.Path;
            var fileName = Path.GetFileName(filePath);
            var targetPath = Path.Combine(targetDir, fileName);
            File.Copy(filePath, targetPath, overwrite: true);
            _logger.LogInformation($"Delivered {fileName} to {targetPath}");
        }
    }

    private string GetOrganizationKey(Document document, string criteria)
    {
        var dirInfo = new DirectoryInfo(document.Path);
        return criteria.ToLowerInvariant() switch
        {
            "type" => document.ProcessedFiles.FirstOrDefault()?.Tags.FirstOrDefault() ?? "unknown",
            "date" => dirInfo.CreationTime.ToString("yyyy-MM-dd"),
            "year" => dirInfo.CreationTime.ToString("yyyy"),
            "month" => document.ProcessedFiles.FirstOrDefault()?.Tags.FirstOrDefault(t => Regex.IsMatch(t, @"\d{4}/\d{2}")) ?? dirInfo.CreationTime.ToString("yyyy-MM"),
            "name" => document.Name,
            _ => dirInfo.CreationTime.ToString("yyyy-MM-dd") // default to date
        };
    }
}