// Generated by Copilot
using System.Threading.Tasks;

namespace DocIngest.Core.Services;

/// <summary>
/// Interface for delivering processed documents to organized locations.
/// Supported organization criteria: "type" (by first tag), "date" (yyyy-MM-dd), "year" (yyyy), "month" (yyyy-MM), "name" (document name).
/// </summary>
public interface IDeliveryService
{
    /// <summary>
    /// Delivers the processed documents for the given document to an organized location.
    /// </summary>
    /// <param name="document">The document to deliver.</param>
    /// <param name="organizationCriteria">The criteria for organization (e.g., "type", "year").</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    Task DeliverAsync(Document document, string organizationCriteria);
}