// Generated by Copilot
namespace DocIngest.Core.Services;

/// <summary>
/// Interface for delivering processed documents to organized locations.
/// Organization can be customized via a callback function that returns the relative path.
/// </summary>
public interface IDeliveryService
{
    /// <summary>
    /// Delivers the processed documents for the given document to an organized location.
    /// </summary>
    /// <param name="document">The document to deliver.</param>
    /// <param name="organizationPathFunc">The function to generate the relative organization path for the document.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    Task DeliverAsync(Document document, Func<Document, string> organizationPathFunc);
}