// Generated by Copilot
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;
using System.Text.Json;
using System.Collections.Generic;

namespace DocIngest.Core.Middlewares;

/// <summary>
/// Middleware that applies AI categorization to documents, adding tags and insights.
/// </summary>
public class AiCategorizationMiddleware : IPipelineMiddleware
{
    private readonly IChatClient _chatClient;
    private readonly ILogger<AiCategorizationMiddleware> _logger;

    public AiCategorizationMiddleware(IChatClient chatClient, ILogger<AiCategorizationMiddleware> _logger)
    {
        _chatClient = chatClient;
        this._logger = _logger;
    }

    public async Task InvokeAsync(PipelineContext context, PipelineDelegate next)
    {
        _logger.LogInformation("Starting AI categorization");

        var documents = context.Items["Documents"] as List<Document>;
        if (documents == null)
        {
            _logger.LogWarning("No documents found in context");
            await next(context);
            return;
        }

        foreach (var document in documents)
        {
            if (string.IsNullOrEmpty(document.Content))
            {
                _logger.LogInformation($"No content to categorize for document {document.Name}");
                continue;
            }

            try
            {
                var messages = new List<ChatMessage>
                {
                    new ChatMessage(ChatRole.User, $"Categorize the following document content. Provide a JSON response with 'tags' as an array of strings (e.g., ['invoice', 'finance']) and 'insights' as an array of strings (key insights like 'Total Amount: $100', 'Date: 2023-01-01').\n\nContent:\n{document.Content}")
                };

                var response = await _chatClient.GetResponseAsync(messages);

                var result = JsonSerializer.Deserialize<AiResponse>(response.Messages.Last().Text);

                if (result != null)
                {
                    document.Tags = result.Tags ?? new List<string>();
                    document.Insights = result.Insights ?? new List<string>();
                }

                _logger.LogInformation($"Categorized document {document.Name} with {document.Tags.Count} tags and {document.Insights.Count} insights");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Error categorizing document {document.Name}");
            }
        }

        _logger.LogInformation("AI categorization completed");
        await next(context);
    }

    private class AiResponse
    {
        public List<string>? Tags { get; set; }
        public List<string>? Insights { get; set; }
    }
}