// Generated by Copilot
using Microsoft.Extensions.Logging;
using DocIngest.Core.Services;
using System.IO;
using System.Text.RegularExpressions;

namespace DocIngest.Core.Middlewares;

/// <summary>
/// Middleware that parses dates from processed text files and adds the month to tags for organization.
/// </summary>
public class DateParsingMiddleware : IPipelineMiddleware
{
    private readonly ILogger<DateParsingMiddleware> _logger;

    public DateParsingMiddleware(ILogger<DateParsingMiddleware> logger)
    {
        _logger = logger;
    }

    public async Task InvokeAsync(PipelineContext context, PipelineDelegate next)
    {
        _logger.LogInformation("Starting date parsing");

        var documents = context.Items["Documents"] as List<Document>;
        if (documents == null)
        {
            _logger.LogWarning("No documents found in context");
            await next(context);
            return;
        }

        foreach (var document in documents)
        {
            foreach (var processedFile in document.ProcessedFiles)
            {
                if (Path.GetExtension(processedFile.Path).ToLower() == ".txt")
                {
                    try
                    {
                        var content = await File.ReadAllTextAsync(processedFile.Path);
                        var dateMatch = Regex.Match(content, @"Date:\s*(\d{4}-\d{2}-\d{2})");
                        if (dateMatch.Success)
                        {
                            var dateStr = dateMatch.Groups[1].Value;
                            var month = dateStr.Substring(0, 4) + "/" + dateStr.Substring(5, 2); // yyyy/MM
                            processedFile.Tags.Add(month);
                            _logger.LogInformation($"Parsed date {dateStr} for {processedFile.Path}, month: {month}");
                        }
                        else
                        {
                            _logger.LogWarning($"No date found in {processedFile.Path}");
                        }
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, $"Failed to parse date from {processedFile.Path}");
                    }
                }
            }
        }

        _logger.LogInformation("Date parsing completed");
        await next(context);
    }
}