// Generated by Copilot
using DocIngest.Core.Services;
using Microsoft.Extensions.Logging;

namespace DocIngest.Core.Middlewares;

/// <summary>
/// Middleware that delivers processed documents to organized locations.
/// Organization is customized via a callback function in the context.
/// </summary>
public class DeliveryMiddleware : IPipelineMiddleware
{
    private readonly IDeliveryService _deliveryService;
    private readonly ILogger<DeliveryMiddleware> _logger;

    public DeliveryMiddleware(IDeliveryService deliveryService, ILogger<DeliveryMiddleware> logger)
    {
        _deliveryService = deliveryService;
        _logger = logger;
    }

    public async Task InvokeAsync(PipelineContext context, PipelineDelegate next)
    {
        _logger.LogInformation("Starting document delivery");

        var documents = context.Items["Documents"] as List<Document>;
        if (documents == null)
        {
            _logger.LogWarning("No documents found in context");
            await next(context);
            return;
        }

        var organizationPathFunc = context.Items.ContainsKey("OrganizationPathFunc") ? context.Items["OrganizationPathFunc"] as Func<Document, string> ?? DefaultOrganizationFunc : DefaultOrganizationFunc;

        foreach (var document in documents)
        {
            if (document.ProcessedFiles.Any())
            {
                await _deliveryService.DeliverAsync(document, organizationPathFunc);
            }
            else
            {
                _logger.LogInformation($"No processed documents for {document.Name}");
            }
        }

        _logger.LogInformation("Document delivery completed");
        await next(context);
    }

    private static string DefaultOrganizationFunc(Document document)
    {
        var dirInfo = new DirectoryInfo(document.Path);
        return dirInfo.CreationTime.ToString("yyyy-MM-dd");
    }
}