// Generated by Copilot
using Microsoft.Extensions.Logging;
using DocIngest.Core.Services;

namespace DocIngest.Core.Middlewares;

/// <summary>
/// Middleware that delivers processed documents to organized locations.
/// Organization criteria defaults to "date" (yyyy-MM-dd), but can be customized via context.
/// </summary>
public class DeliveryMiddleware : IPipelineMiddleware
{
    private readonly IDeliveryService _deliveryService;
    private readonly ILogger<DeliveryMiddleware> _logger;

    public DeliveryMiddleware(IDeliveryService deliveryService, ILogger<DeliveryMiddleware> logger)
    {
        _deliveryService = deliveryService;
        _logger = logger;
    }

    public async Task InvokeAsync(PipelineContext context, PipelineDelegate next)
    {
        _logger.LogInformation("Starting document delivery");

        var documents = context.Items["Documents"] as List<Document>;
        if (documents == null)
        {
            _logger.LogWarning("No documents found in context");
            await next(context);
            return;
        }

        var organizationCriteria = context.Items.ContainsKey("OrganizationCriteria") ? context.Items["OrganizationCriteria"] as string ?? "date" : "date";

        foreach (var document in documents)
        {
            if (document.ProcessedFiles.Any())
            {
                await _deliveryService.DeliverAsync(document, organizationCriteria);
            }
            else
            {
                _logger.LogInformation($"No processed documents for {document.Name}");
            }
        }

        _logger.LogInformation("Document delivery completed");
        await next(context);
    }
}