// Generated by Copilot
using System.IO;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;

namespace DocIngest.Core.Middlewares;

/// <summary>
/// Middleware that traverses a root folder, identifies subfolders, and collects all files from each subfolder,
/// treating each subfolder as one document with related files.
/// </summary>
public class DocumentTraversalMiddleware : IPipelineMiddleware
{
    private readonly string _rootFolderPath;
    private readonly ILogger? _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="DocumentTraversalMiddleware"/> class.
    /// </summary>
    /// <param name="rootFolderPath">The path to the root folder to traverse.</param>
    /// <param name="logger">Optional logger for error handling.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="rootFolderPath"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown when <paramref name="rootFolderPath"/> does not exist or is not a directory.</exception>
    public DocumentTraversalMiddleware(string rootFolderPath, ILogger? logger = null)
    {
        _rootFolderPath = rootFolderPath ?? throw new ArgumentNullException(nameof(rootFolderPath));
        if (!Directory.Exists(_rootFolderPath))
        {
            throw new ArgumentException($"The specified root folder path does not exist: {_rootFolderPath}", nameof(rootFolderPath));
        }
        _logger = logger;
    }

    /// <summary>
    /// Invokes the middleware to traverse folders and collect documents.
    /// </summary>
    /// <param name="context">The pipeline context.</param>
    /// <param name="next">The next middleware in the pipeline.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    public async Task InvokeAsync(PipelineContext context, PipelineDelegate next)
    {
        var documents = new List<Document>();

        try
        {
            // Enumerate subfolders
            foreach (var subfolder in Directory.EnumerateDirectories(_rootFolderPath))
            {
                try
                {
                    var document = new Document
                    {
                        Path = subfolder,
                        Name = System.IO.Path.GetFileName(subfolder)
                    };

                    // Enumerate files in the subfolder
                    foreach (var filePath in Directory.EnumerateFiles(subfolder))
                    {
                        try
                        {
                            var fileInfo = new System.IO.FileInfo(filePath);
                            document.Files.Add(new FileInfo
                            {
                                Path = filePath,
                                Name = fileInfo.Name,
                                LastModified = fileInfo.LastWriteTime,
                                Size = fileInfo.Length
                            });
                        }
                        catch (UnauthorizedAccessException ex)
                        {
                            _logger?.LogWarning(ex, "Access denied for file: {FilePath}", filePath);
                            // Skip this file and continue
                        }
                        catch (IOException ex)
                        {
                            _logger?.LogWarning(ex, "I/O error accessing file: {FilePath}", filePath);
                            // Skip this file and continue
                        }
                        catch (Exception ex)
                        {
                            _logger?.LogWarning(ex, "Failed to get info for file: {FilePath}", filePath);
                            // Skip this file and continue
                        }
                    }

                    documents.Add(document);
                }
                catch (UnauthorizedAccessException ex)
                {
                    _logger?.LogWarning(ex, "Access denied for subfolder: {Subfolder}", subfolder);
                    // Skip this subfolder and continue
                }
                catch (IOException ex)
                {
                    _logger?.LogWarning(ex, "I/O error accessing subfolder: {Subfolder}", subfolder);
                    // Skip this subfolder and continue
                }
                catch (Exception ex)
                {
                    _logger?.LogWarning(ex, "Failed to process subfolder: {Subfolder}", subfolder);
                    // Skip this subfolder and continue
                }
            }
        }
        catch (UnauthorizedAccessException ex)
        {
            _logger?.LogError(ex, "Access denied for root folder: {RootFolder}", _rootFolderPath);
            // Proceed with empty list
        }
        catch (IOException ex)
        {
            _logger?.LogError(ex, "I/O error accessing root folder: {RootFolder}", _rootFolderPath);
            // Proceed with empty list
        }
        catch (Exception ex)
        {
            _logger?.LogError(ex, "Failed to enumerate directories in root folder: {RootFolder}", _rootFolderPath);
            // If root folder is inaccessible, we can still proceed or halt; for now, proceed with empty list
        }

        // If no subfolders, treat files in root as individual documents
        if (!documents.Any())
        {
            try
            {
                foreach (var filePath in Directory.EnumerateFiles(_rootFolderPath))
                {
                    try
                    {
                        var fileInfo = new System.IO.FileInfo(filePath);
                        var document = new Document
                        {
                            Path = filePath,
                            Name = fileInfo.Name
                        };
                        document.Files.Add(new FileInfo
                        {
                            Path = filePath,
                            Name = fileInfo.Name,
                            LastModified = fileInfo.LastWriteTime,
                            Size = fileInfo.Length
                        });
                        documents.Add(document);
                    }
                    catch (Exception ex)
                    {
                        _logger?.LogWarning(ex, "Failed to process file: {FilePath}", filePath);
                    }
                }
            }
            catch (Exception ex)
            {
                _logger?.LogError(ex, "Failed to enumerate files in root folder: {RootFolder}", _rootFolderPath);
            }
        }

        // Store the documents in the context
        context.Items["Documents"] = documents;

        // Call the next middleware
        await next(context);
    }
}