// Generated by Copilot
using System.IO;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;

namespace DocIngest.Core.Middlewares;

/// <summary>
/// Middleware that traverses a root folder, identifies subfolders, and collects all files from each subfolder,
/// treating each subfolder as one document with related files.
/// </summary>
public class DocumentTraversalMiddleware : IPipelineMiddleware
{
    private readonly string _rootFolderPath;
    private readonly ILogger? _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="DocumentTraversalMiddleware"/> class.
    /// </summary>
    /// <param name="rootFolderPath">The path to the root folder to traverse.</param>
    /// <param name="logger">Optional logger for error handling.</param>
    public DocumentTraversalMiddleware(string rootFolderPath, ILogger? logger = null)
    {
        _rootFolderPath = rootFolderPath ?? throw new ArgumentNullException(nameof(rootFolderPath));
        _logger = logger;
    }

    /// <summary>
    /// Invokes the middleware to traverse folders and collect documents.
    /// </summary>
    /// <param name="context">The pipeline context.</param>
    /// <param name="next">The next middleware in the pipeline.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    public async Task InvokeAsync(PipelineContext context, PipelineDelegate next)
    {
        var documents = new List<Document>();

        try
        {
            // Enumerate subfolders
            foreach (var subfolder in Directory.EnumerateDirectories(_rootFolderPath))
            {
                try
                {
                    var document = new Document
                    {
                        Path = subfolder,
                        Name = System.IO.Path.GetFileName(subfolder)
                    };

                    // Enumerate files in the subfolder
                    foreach (var filePath in Directory.EnumerateFiles(subfolder))
                    {
                        try
                        {
                            var fileInfo = new System.IO.FileInfo(filePath);
                            document.Files.Add(new FileInfo
                            {
                                Path = filePath,
                                Name = fileInfo.Name,
                                LastModified = fileInfo.LastWriteTime,
                                Size = fileInfo.Length
                            });
                        }
                        catch (Exception ex)
                        {
                            _logger?.LogWarning(ex, "Failed to get info for file: {FilePath}", filePath);
                            // Skip this file and continue
                        }
                    }

                    documents.Add(document);
                }
                catch (Exception ex)
                {
                    _logger?.LogWarning(ex, "Failed to process subfolder: {Subfolder}", subfolder);
                    // Skip this subfolder and continue
                }
            }
        }
        catch (Exception ex)
        {
            _logger?.LogError(ex, "Failed to enumerate directories in root folder: {RootFolder}", _rootFolderPath);
            // If root folder is inaccessible, we can still proceed or halt; for now, proceed with empty list
        }

        // Store the documents in the context
        context.Items["Documents"] = documents;

        // Call the next middleware
        await next(context);
    }
}